<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Job>
 */
class JobFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {

        $requirements = [
            // Math & Physics (15 skills)
            'Calculus',
            'Linear Algebra',
            'Differential Equations',
            'Mathematical Modelling',
            'Number Theory',
            'Probability',
            'Statistics',
            'Statistical Analysis',
            'Data Mining',
            'Regression Analysis',
            'Time Series Analysis',
            'Discrete Mathematics',
            'Combinatorics',
            'Game Theory',
            'Quantum Physics',

            // Programming (20 skills)
            'Machine Learning',
            'Artificial Intelligence',
            'Deep Learning',
            'Natural Language Processing',
            'Data Structures',
            'Algorithms',
            'Python Programming',
            'JavaScript',
            'Java',
            'C++',
            'Ruby',
            'SQL',
            'PHP',
            'R Programming',
            'C Programming',
            'Swift',
            'Kotlin',
            'HTML/CSS',
            'React',
            'Angular',
            'Node.js'
        ];

        $questions = [
            "What is a variable in programming?",
            "What is the difference between a class and an object?",
            "What is a function?",
            "What is recursion?",
            "Explain the concept of inheritance in object-oriented programming.",
            "What is polymorphism?",
            "What is the difference between an array and a list?",
            "What is an algorithm?",
            "What is the purpose of a database index?",
            "What is the difference between SQL and NoSQL databases?",
            "Explain the concept of a linked list.",
            "What is a hash table?",
            "What is the difference between a stack and a queue?",
            "What is the time complexity of binary search?",
            "Explain the concept of a binary tree.",
            "What is a hash function?",
            "What is the difference between HTTP and HTTPS?",
            "What is the purpose of a constructor in object-oriented programming?",
            "What is the difference between a synchronous and asynchronous function?",
            "Explain the use of the `final` keyword in Java.",
            "What is a closure in JavaScript?",
            "What is a promise in JavaScript?",
            "What is the purpose of a `try-catch` block?",
            "What is the difference between `let`, `const`, and `var` in JavaScript?",
            "What is event bubbling in JavaScript?",
            "What is the purpose of the `this` keyword in JavaScript?",
            "What is a callback function?",
            "What is the difference between `==` and `===` in JavaScript?",
            "What are the differences between GET and POST HTTP methods?",
            "What is AJAX?",
            "What is the purpose of a session in web development?",
            "What is the MVC pattern in software design?",
            "What is the purpose of a foreign key in databases?",
            "Explain the difference between static and dynamic typing in programming languages.",
            "What is a framework?",
            "What is the difference between Git and GitHub?",
            "What is an API?",
            "What is RESTful API?",
            "What is an IDE (Integrated Development Environment)?",
            "What is the purpose of the `async` and `await` keywords?",
            "What is the difference between `splice()` and `slice()` in JavaScript?",
            "What is a microservice architecture?",
            "What is a closure in PHP?",
            "What is the `foreach` loop in PHP?",
            "What is the purpose of a migration in Laravel?",
            "What is an ORM (Object-Relational Mapping)?",
            "What is the purpose of a router in a web application?",
            "What is a middleware in Laravel?",
            "What is CSRF (Cross-Site Request Forgery)?",
            "What is XSS (Cross-Site Scripting)?",
            "What is SQL injection?",
            "What is Docker?",
            "What is Kubernetes?",
            "What is Git branching?",
            "What is a pull request?",
            "What is a deadlock in programming?",
            "What is multi-threading?",
            "What is the purpose of the `__construct()` method in PHP?",
            "What is dependency injection?",
            "What is the SOLID principle in object-oriented design?",
            "What is normalization in databases?",
            "What is denormalization in databases?",
            "What is the purpose of a primary key?",
            "What is an aggregate function in SQL?",
            "What is a view in SQL?",
            "What is a stored procedure in SQL?",
            "What is the difference between `INNER JOIN` and `LEFT JOIN` in SQL?",
            "What is the purpose of `GROUP BY` in SQL?",
            "What is `ORDER BY` in SQL?",
            "What is the difference between `UNION` and `JOIN` in SQL?",
            "What is the purpose of `HAVING` in SQL?",
            "What is the difference between `PUT` and `PATCH` HTTP methods?",
            "What is a RESTful web service?",
            "What is the purpose of CORS (Cross-Origin Resource Sharing)?",
            "What is OAuth?",
            "What is JWT (JSON Web Token)?",
            "What is the difference between NoSQL and SQL databases?",
            "What is the purpose of the `echo` statement in PHP?",
            "What is a CDN (Content Delivery Network)?",
            "What is the difference between front-end and back-end development?",
            "What is the purpose of the `npm` package manager?",
            "What is the difference between a GET and a POST request?",
            "What is the purpose of cookies in web development?",
            "What is the difference between cookies and sessions?",
            "What is the purpose of HTML meta tags?",
            "What is the use of the `console.log()` method?",
            "What is event delegation in JavaScript?",
            "What is a promise chain?",
            "What is the purpose of the `super` keyword?",
            "What is the difference between `var`, `let`, and `const` in JavaScript?",
            "What is a singleton pattern in object-oriented design?",
            "What is a factory pattern in design?",
            "What is dependency injection in PHP?",
            "What is MVC?",
            "What is the difference between `map()` and `forEach()` in JavaScript?",
            "What is a service provider in Laravel?",
            "What is the purpose of a web server?",
            "What is an SSL certificate?",
            "What is a web socket?",
            "What is the difference between a script and a stylesheet?",
            "What is the use of `console.error()` in JavaScript?",
            "What is a static website?",
            "What is a dynamic website?",
            "What is the difference between a method and a function in programming?",
            "What is the difference between a deep copy and a shallow copy in programming?",
            "What is JSON?",
            "What is the use of the `filter()` function in JavaScript?",
            "What is the use of the `reduce()` function in JavaScript?",
            "What is a CLI (Command Line Interface)?",
            "What is the purpose of a shell script?",
            "What is the difference between a script and a program?",
            "What is WebAssembly?",
            "What is the difference between procedural and object-oriented programming?",
            "What is the purpose of an exception handler?",
            "What is the difference between `throw` and `throws` in Java?",
            "What is the difference between `switch` and `if-else` in programming?",
            "What is an IDE?",
            "What is the difference between public, private, and protected access modifiers?"
        ];
        $selectedRequirements = $this->faker->randomElements($requirements, $count = rand(4, 8));
        $selectedQuestions = $this->faker->randomElements($questions, $count = rand(3, 7));


        return [
            'title' => fake()->jobTitle(),
            'description' => fake()->sentence($nbWords = 100, $variableNbWords = true),
            'type' => fake()->randomElement($array = array('Full-time', 'Part-time', 'Contractual')),
            'hours_start' => "09:00:00",
            'hours_end' => "17:00:00",
            'requirements' => json_encode($selectedRequirements),
            'questions' => json_encode($selectedQuestions),
        ];
    }
}
